In [ ]:
pd.options.display.max_rows = 999

NameError: ignored

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline


# Load data.

data = pd.read_csv('/content/Train value with labels.csv')


# Merge data and labels together in one dataframe.

In [2]:
data.head(3)

      id  amount_tsh  ... waterpoint_type_group status_group
0  69572      6000.0  ...    communal standpipe   functional
1   8776         0.0  ...    communal standpipe   functional
2  34310        25.0  ...    communal standpipe   functional

[3 rows x 41 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 41 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     59400 non-null  int64
 1   amount_tsh             59400 non-null  float64
 2   date_recorded          59400 non-null  object
 3   funder                 55765 non-null  object
 4   gps_height             59400 non-null  int64
 5   installer              55745 non-null  object
 6   longitude              59400 non-null  float64
 7   latitude               59400 non-null  float64
 8   wpt_name               59400 non-null  object
 9   num_private            59400 non-null  int64
 10  basin                  59400 non-null  object
 11  subvillage             59029 non-null  object
 12  region                 59400 non-null  object
 13  region_code            59400 non-null  int64
 14  district_code          59400 non-null  int64
 15  lga                    59400 non-null  object
 16  ward                   59400 non-null  object
 17  population             59400 non-null  int64
 18  public_meeting         56066 non-null  object
 19  recorded_by            59400 non-null  object
 20  scheme_management      55523 non-null  object
 21  scheme_name            31234 non-null  object
 22  permit                 56344 non-null  object
 23  construction_year      59400 non-null  int64
 24  extraction_type        59400 non-null  object
 25  extraction_type_group  59400 non-null  object
 26  extraction_type_class  59400 non-null  object
 27  management             59400 non-null  object
 28  management_group       59400 non-null  object
 29  payment                59400 non-null  object
 30  payment_type           59400 non-null  object
 31  water_quality          59400 non-null  object
 32  quality_group          59400 non-null  object
 33  quantity               59400 non-null  object
 34  quantity_group         59400 non-null  object
 35  source                 59400 non-null  object
 36  source_type            59400 non-null  object
 37  source_class           59400 non-null  object
 38  waterpoint_type        59400 non-null  object
 39  waterpoint_type_group  59400 non-null  object
 40  status_group           59400 non-null  object
dtypes: float64(3), int64(7), object(31)
memory usage: 18.6+ MB

In [5]:
data.shape

(59400, 41)

In [7]:
data.head(10)

      id  amount_tsh  ... waterpoint_type_group    status_group
0  69572      6000.0  ...    communal standpipe      functional
1   8776         0.0  ...    communal standpipe      functional
2  34310        25.0  ...    communal standpipe      functional
3  67743         0.0  ...    communal standpipe  non functional
4  19728         0.0  ...    communal standpipe      functional
5   9944        20.0  ...    communal standpipe      functional
6  19816         0.0  ...             hand pump  non functional
7  54551         0.0  ...             hand pump  non functional
8  53934         0.0  ...             hand pump  non functional
9  46144         0.0  ...             hand pump      functional

[10 rows x 41 columns]

In [6]:
data.tail(3)

          id  amount_tsh  ... waterpoint_type_group status_group
59397  37057         0.0  ...             hand pump   functional
59398  31282         0.0  ...             hand pump   functional
59399  26348         0.0  ...             hand pump   functional

[3 rows x 41 columns]

In [8]:
# Check for nulls.

data.apply(lambda x: sum(x.isnull()))

id                           0
amount_tsh                   0
date_recorded                0
funder                    3635
gps_height                   0
installer                 3655
longitude                    0
latitude                     0
wpt_name                     0
num_private                  0
basin                        0
subvillage                 371
region                       0
region_code                  0
district_code                0
lga                          0
ward                         0
population                   0
public_meeting            3334
recorded_by                  0
scheme_management         3877
scheme_name              28166
permit                    3056
construction_year            0
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_group                0
quantity                     0
quantity_group               0
source                       0
source_type                  0
source_class                 0
waterpoint_type              0
waterpoint_type_group        0
status_group                 0
dtype: int64

In [9]:
data['public_meeting']

0        True
1         NaN
2        True
3        True
4        True
         ...
59395    True
59396    True
59397    True
59398    True
59399    True
Name: public_meeting, Length: 59400, dtype: object

In [10]:
data['scheme_name']

0                              Roman
1                                NaN
2        Nyumba ya mungu pipe scheme
3                                NaN
4                                NaN
                    ...
59395         Losaa Kia water supply
59396    Ikondo electrical water sch
59397                            NaN
59398                            NaN
59399                            NaN
Name: scheme_name, Length: 59400, dtype: object

##Missing value Impute

In [ ]:
# Create a function to reduce the amount of dummy columns needed whilst maintaining the 
# information contained in the column.

def funder_wrangler(row):  
    '''Keep top 5 values and set the rest to 'other'''

    if row['funder']=='Government Of Tanzania':
        return 'gov'
    elif row['funder']=='Danida':
        return 'danida'
    elif row['funder']=='Hesawa':
        return 'hesawa'
    elif row['funder']=='Rwssp':
        return 'rwssp'
    elif row['funder']=='World Bank':
        return 'world_bank'    
    else:
        return 'other'
    
df['funder'] = df.apply(lambda row: funder_wrangler(row), axis=1)

In [ ]:
df.installer.value_counts()

DWE               21751
Government         2282
RWE                1498
Commu              1347
DANIDA             1305
                  ...
Mungaya               1
Samweli               1
SINGIDA  YETU         1
FinWter               1
CHONJA CHARLES        1
Name: installer, Length: 2410, dtype: int64

In [ ]:
# Create a function to reduce the amount of dummy columns needed whilst maintaining the 
# information contained in the column.

def installer_wrangler(row):  
    '''Keep top 5 values and set the rest to 'other'''

    if row['installer']=='DWE':
        return 'dwe'
    elif row['installer']=='Government':
        return 'gov'
    elif row['installer']=='RWE':
        return 'rwe'
    elif row['installer']=='Commu':
        return 'commu'
    elif row['installer']=='DANIDA':
        return 'danida'    
    else:
        return 'other'
    
df['installer'] = df.apply(lambda row: installer_wrangler(row), axis=1)

In [ ]:
#Drop Subvillage

df = df.drop('subvillage', axis=1)

In [ ]:
# Replace Public_meeting missing values by unknown

df.public_meeting = df.public_meeting.fillna('Unknown')

In [11]:

data.scheme_management.value_counts()

VWC                 36793
WUG                  5206
Water authority      3153
WUA                  2883
Water Board          2748
Parastatal           1680
Private operator     1063
Company              1061
Other                 766
SWC                    97
Trust                  72
None                    1
Name: scheme_management, dtype: int64

In [ ]:

def scheme_management_wrangler(row):  
    '''Keep top 5 values and set the rest to 'other'''

    if row['scheme_management']=='VWC':
        return 'vwc'
    elif row['scheme_management']=='WUG':
        return 'wug'
    elif row['scheme_management']=='Water authority':
        return 'wtr_auth'
    elif row['scheme_management']=='WUA':
        return 'wua'
    elif row['scheme_management']=='Water Board':
        return 'wtr_brd'    
    else:
        return 'other'
    
df['scheme_management'] = df.apply(lambda row: scheme_management_wrangler(row), axis=1)

In [ ]:
df.scheme_name.value_counts()

K                       858
None                    794
Borehole                704
Chalinze wate           501
M                       490
                       ...
Mradi wa maji wa kag      1
Kwasenenge Group          1
Welela Shallow well       1
Nampemba                  1
Mlima wa Nyasho           1
Name: scheme_name, Length: 2868, dtype: int64

In [ ]:
#Drop scheme_name

df = df.drop('scheme_name', axis=1)

In [ ]:
#Replace permit missing values by unknown

df.permit = df.permit.fillna('Unknown')

In [ ]:
# Check for nulls.

df.apply(lambda x: sum(x.isnull()))

id                           0
amount_tsh                   0
date_recorded                0
funder                       0
gps_height                   0
installer                    0
longitude                    0
latitude                     0
wpt_name                     0
num_private                  0
basin                        0
region                       0
region_code                  0
district_code                0
lga                          0
ward                         0
population                   0
public_meeting               0
recorded_by                  0
scheme_management            0
permit                       0
construction_year            0
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_group                0
quantity                     0
quantity_group               0
source                       0
source_type                  0
source_class                 0
waterpoint_type              0
waterpoint_type_group        0
status_group             14850
ind                          0
dtype: int64

In [ ]:
#Drop ind

df = df.drop('ind', axis=1)

In [ ]:

#View all the cateforical Value
obj_df = df.select_dtypes(include=['object']).copy()
obj_df.head()

  date_recorded funder installer              wpt_name                    basin  ...           source_type source_class              waterpoint_type waterpoint_type_group    status_group
0    2011-03-14  other     other                  none               Lake Nyasa  ...                spring  groundwater           communal standpipe    communal standpipe      functional
1    2013-03-06  other     other              Zahanati            Lake Victoria  ...  rainwater harvesting      surface           communal standpipe    communal standpipe      functional
2    2013-02-25  other     other           Kwa Mahundi                  Pangani  ...                   dam      surface  communal standpipe multiple    communal standpipe      functional
3    2013-01-28  other     other  Zahanati Ya Nanyumbu  Ruvuma / Southern Coast  ...              borehole  groundwater  communal standpipe multiple    communal standpipe  non functional
4    2011-07-13  other     other               Shuleni            Lake Victoria  ...  rainwater harvesting      surface           communal standpipe    communal standpipe      functional

[5 rows x 29 columns]

In [ ]:

#View object columns
obj_df.columns

Index(['date_recorded', 'funder', 'installer', 'wpt_name', 'basin', 'region', 'lga', 'ward', 'public_meeting', 'recorded_by', 'scheme_management', 'permit', 'extraction_type', 'extraction_type_group', 'extraction_type_class', 'management', 'management_group', 'payment', 'payment_type', 'water_quality', 'quality_group', 'quantity', 'quantity_group', 'source', 'source_type', 'source_class', 'waterpoint_type', 'waterpoint_type_group', 'status_group'], dtype='object')

In [ ]:
#Create dummy variable for all object columns
waterpump_data = pd.get_dummies(data=df, columns=['date_recorded', 'funder', 'installer', 'wpt_name', 'basin', 'region', 'lga', 'ward', 'public_meeting', 'recorded_by', 'scheme_management', 
                                                           'permit', 'extraction_type', 'extraction_type_group', 'extraction_type_class', 'management', 'management_group', 'payment', 'payment_type',
                                                           'water_quality', 'quality_group', 'quantity', 'quantity_group', 'source', 'source_type', 'source_class', 'waterpoint_type', 
                                                           'waterpoint_type_group', 'status_group'], drop_first=True)

In [ ]:
waterpump_data

          id  amount_tsh  gps_height  longitude   latitude  ...  waterpoint_type_group_hand pump  waterpoint_type_group_improved spring  waterpoint_type_group_other  status_group_functional needs repair  status_group_non functional
0      69572      6000.0        1390  34.938093  -9.856322  ...                                0                                      0                            0                                     0                            0
1       8776         0.0        1399  34.698766  -2.147466  ...                                0                                      0                            0                                     0                            0
2      34310        25.0         686  37.460664  -3.821329  ...                                0                                      0                            0                                     0                            0
3      67743         0.0         263  38.486161 -11.155298  ...                                0                                      0                            0                                     0                            1
4      19728         0.0           0  31.130847  -1.825359  ...                                0                                      0                            0                                     0                            0
...      ...         ...         ...        ...        ...  ...                              ...                                    ...                          ...                                   ...                          ...
14845  39307         0.0          34  38.852669  -6.582841  ...                                0                                      0                            0                                     0                            0
14846  18990      1000.0           0  37.451633  -5.350428  ...                                1                                      0                            0                                     0                            0
14847  28749         0.0        1476  34.739804  -4.585587  ...                                0                                      0                            0                                     0                            0
14848  33492         0.0         998  35.432732 -10.584159  ...                                0                                      0                            0                                     0                            0
14849  68707         0.0         481  34.765054 -11.226012  ...                                0                                      0                            0                                     0                            0

[74250 rows x 48441 columns]

In [ ]:

# Allocate dataset, first 1460 rows contain Saleprice, and remainning doesn't have SalePrice.
N_train = 14850
status_group_data = df[:N_train]
status_group_predict = df[N_train:]


print("Missing values for status_group_data:", np.any(status_group_data.isnull().values))
print("Missing values for the test:", np.any(status_group_predict.isnull().values))

Missing values for status_group_data: False
Missing values for the test: True

In [ ]:

#Load Liabry
import copy 

#Allocate variable to X and target variable 'SalePrice' to y 
y = status_group_data[(['status_group'])]
X = copy.deepcopy(status_group_data).drop(['status_group'], axis=1)
X_predict_statusgroup = copy.deepcopy(status_group_predict).drop(['status_group'], axis=1)

In [ ]:
X.head(3)

      id  amount_tsh date_recorded funder  gps_height  ...                source           source_type  source_class              waterpoint_type  waterpoint_type_group
0  69572      6000.0    2011-03-14  other        1390  ...                spring                spring   groundwater           communal standpipe     communal standpipe
1   8776         0.0    2013-03-06  other        1399  ...  rainwater harvesting  rainwater harvesting       surface           communal standpipe     communal standpipe
2  34310        25.0    2013-02-25  other         686  ...                   dam                   dam       surface  communal standpipe multiple     communal standpipe

[3 rows x 38 columns]

In [ ]:
y.head()

     status_group
0      functional
1      functional
2      functional
3  non functional
4      functional

In [ ]:
#Split the data after clean
test, train = df[df["ind"].eq("test")], df[df["ind"].eq("train")]